### ISSUE TITLE
Problem with articles/pi-chudnovsky/index.md

### ISSUE THREAD

**Issue by Hermann12** [ncw/www#1]
Traceback (most recent call last):
  File "D:\....\PiArithmetic.py", line 58, in <module>
    res = pi_chudnovsky_bs(digits)
  File "D:\....\PiArithmetic.py", line 53, in pi_chudnovsky_bs
    sqrtC = (10005*one_squared).sqrt()
AttributeError: 'mpz' object has no attribute 'sqrt'

I have installed gmpy2-2.1.5 and Python 3.11.2

**Comment by ncw** [comment]
Thank you for the bug report.

They seem to have removed the `sqrt` attribute from `mpz`  and replaced it with a package global.

I've fixed the script now - please download again.
